# Generated by Django 3.0.3 on 2020-02-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('score', models.CharField(max_length=50)),
                ('date_created', models.CharField(max_length=50)),
            ],
        ),
    ]
